spring:
  application.name: FirstRestApp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project3
    username: postgres
    password: marviniscool
  jpa.properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
  sql.init.mode: always