DROP TABLE IF EXISTS measurements;
DROP TABLE IF EXISTS sensor;

CREATE TABLE sensor(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL UNIQUE CHECK(length(name) BETWEEN 3 AND 30),
    created_at timestamp NOT NULL,
    created_by varchar(30) NOT NULL
);

CREATE TABLE measurements(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value int NOT NULL CHECK(value BETWEEN -100 and 100),
    raining bool NOT NULL,
    measure_time timestamp NOT NULL,
    measure_by int REFERENCES sensor(id)
);
